spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:log4jdbc:mysql://192.168.241.130:3306/jdbc
    driver-class-name: net.sf.log4jdbc.DriverSpy
#    schema:
#      - classpath:department.sql
    type: com.alibaba.druid.pool.DruidDataSource

    initialization-mode: ALWAYS


    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1 from dual
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
#    filters: stat, wall, log4j
