spring:
  application:
    name: consumer-user   # 最终会落实到 注册中心的Application 即Web Eureka页面中

server:
  port: 8200
eureka:
  instance:
    prefer-ip-address: true  # 注册服务时 使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


