spring:
  datasource:
    url: jdbc:mysql://192.168.230.129:3306/jpa
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 更新或者创建数据表

    show-sql: true # 控制台显示sql




